title: Immanuel Satya
author: Immanuel Satya
email: satya.immanuel@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I currently do research for fun, mainly about spatial methods and regional economics. Aspiring academic.

# social links
##twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  soegampars # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
