title: Personal Academic Blog
author: Immanuel Satya
email: satya.immanuel@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This blog is currently under development. In the future, this blog will be used to
  provide updates about my projects and my academic activity.

# social links
##twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  soegampars # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-slate
